import { describe,expect,it } from 'vitest'
import { filterCocktails,getCocktailById,getCocktailBySlug,getIngredientById,getIngredientCoverage,resolveRecipe,searchCocktails } from './cocktails'

describe('cocktail utilities',()=>{
  it('looks up known and unknown records',()=>{expect(getIngredientById('gin')?.name).toBe('Gin');expect(getIngredientById('missing')).toBeUndefined();expect(getCocktailBySlug('basil-beauty')?.name).toBe('Basil Beauty');expect(getCocktailById('missing')).toBeUndefined()})
  it('resolves recipe lines',()=>{const resolved=resolveRecipe(getCocktailById('basil-beauty')!);expect(resolved).toHaveLength(6);expect(resolved[0]?.ingredient.name).toBe('Passion Fruit')})
  it('searches names, aliases and ingredients case-insensitively',()=>{expect(searchCocktails('CITROEN').map(c=>c.id)).toContain('basil-beauty');expect(searchCocktails('ruby equal-parts').map(c=>c.id)).toContain('negroni');expect(searchCocktails('')).toHaveLength(25)})
  it('composes filters and returns safe empty results',()=>{expect(filterCocktails({origin:['mocktail']})).toHaveLength(3);expect(filterCocktails({glass:['martini'],alcoholic:true}).map(c=>c.id)).toContain('basil-beauty');expect(filterCocktails({tags:['does-not-exist']})).toEqual([]);expect(filterCocktails({})).toHaveLength(25)})
  it('uses OR semantics within origin and ingredient groups',()=>{const results=filterCocktails({origin:['classic','modern'],ingredientIds:['gin','citron-vodka']});expect(results.map(c=>c.id)).toEqual(expect.arrayContaining(['negroni','basil-beauty']));expect(results.every(c=>c.origin==='classic'||c.origin==='modern')).toBe(true);expect(results.every(c=>c.ingredients.some(line=>line.ingredientId==='gin'||line.ingredientId==='citron-vodka'))).toBe(true)})
  it('uses AND semantics across origin, ingredient, and glass groups',()=>{expect(filterCocktails({origin:['classic'],ingredientIds:['gin','citron-vodka'],glass:['rocks']}).map(c=>c.id)).toEqual(['negroni'])})
  it('matches canonical ingredient IDs',()=>{expect(filterCocktails({ingredientIds:['citron-vodka']}).map(c=>c.id)).toEqual(['basil-beauty'])})
  it('uses OR semantics for prominent tastes with scores of at least four',()=>{const results=filterCocktails({prominentTastes:['bitter','fruity']});expect(results.map(c=>c.id)).toEqual(expect.arrayContaining(['negroni','basil-beauty']));expect(results.every(c=>c.taste.bitter>=4||c.taste.fruity>=4)).toBe(true)})
  it('includes taste scores at the threshold and excludes scores below it',()=>{const ids=filterCocktails({prominentTastes:['fruity']}).map(c=>c.id);expect(ids).toContain('paloma');expect(ids).not.toContain('margarita')})
  it('combines ingredient and prominent taste groups',()=>{const results=filterCocktails({ingredientIds:['gin'],prominentTastes:['bitter']});expect(results.map(c=>c.id)).toContain('negroni');expect(results.every(c=>c.ingredients.some(line=>line.ingredientId==='gin')&&c.taste.bitter>=4)).toBe(true)})
  it('reports deduplicated ingredient coverage',()=>{const coverage=getIngredientCoverage(getCocktailById('negroni')!,['gin','campari','gin']);expect(coverage.available).toHaveLength(2);expect(coverage.missing).toHaveLength(1);expect(coverage.ratio).toBeCloseTo(2/3)})
})
